console.log('Me: Hello World')
console.log("World: (world's keep silent")
console.log("Me: HELLO WORLD!!!!")
console.log("World: (still silent)")
console.log("Me: I SAID HELLO WOOORRLLLDDD!!!!")
console.log("world: Earthquacke")